version: '3.8'

services:
  backend:
    build: .
    ports:
      - "0.0.0.0:443:443"
    depends_on:
      - mongodb
    env_file:
      - .env_prod
    volumes:
      - ./certs:/app/certs:ro

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"